spring:
  application:
    name: process-element-example

server:
  port: 8081
  error:
    include-message: always

camunda:
  bpm:
    admin-user:
      id: demo
      firstName: demo
      password: demo
    database:
      schema-update: true
    auto-deployment-enabled: true
    history-level: activity